### ISSUE TITLE
More repo code that doesn't match the corresponding video

### ISSUE THREAD

**Issue by billdavisjr** [Code-Institute-Solutions/WorkingWithExternalResources#2]
in WorkingWithExternalResources/03-DataAndTheDOM/05-tabular_data_part_three/main.js the code does not at all match what's in the corresponding video in the course (Tabular Data - Part three).  This is similar to the other one I posted.  Both are using code (the same code I think) from a couple of videos back.

**Comment by NielMc** [comment]
Updated repository to match video code.
